spring.activemq.broker-url=${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
spring.activemq.user=${ACTIVEMQ_USER:admin}
spring.activemq.password=${ACTIVEMQ_PASSWORD:admin}

lab.p2p.queue=lab.m2.ticket.work
lab.p2p.concurrency=2-2
