package com.reclamos.backend.entity;

public enum ActivityType {
    TICKET_CREATED,
    REVIEW_STARTED,
    STATE_CHANGED,
    ROUTED,
    RETURNED_BY_AREA,
    PRIORITY_CHANGED,
    ESCALATED,
    INFORMATION_REQUIRED,
    INFORMATION_PROVIDED,
    PROGRESS_REPORTED,
    DUPLICATE_LINKED,
    RESOLVED,
    REOPENED,
    CANCELLATION_REQUESTED,
    CANCELLATION_APPROVED,
    CANCELLATION_REJECTED,
    CANCELLED,
    CLOSED,
    PUBLIC_MESSAGE_SENT,
    INTERNAL_MESSAGE_ADDED,
    ATTACHMENT_ADDED
}
