package com.reclamos.backend.entity;

public enum NotificationType {
    TICKET_REGISTERED,
    INFORMATION_REQUIRED,
    INFORMATION_PROVIDED,
    RESOLVED,
    CANCELLED,
    CONFIRMATION_REQUIRED,
    CLOSED,
    REOPENED,
    PUBLIC_MESSAGE_RECEIVED,
    INTERNAL_MESSAGE_RECEIVED,
    STATUS_CHANGED,
    SLA_NEAR_DUE,
    SLA_BREACHED
}