CREATE TABLE module_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    citizen_id UUID NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(254),
    phone VARCHAR(50),
    profile_image_url VARCHAR(500),
    role VARCHAR(30) NOT NULL,
    area_id VARCHAR(100),
    preferred_notification_channel VARCHAR(30),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    last_synced_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_module_user_citizen_id UNIQUE (citizen_id),
    CONSTRAINT ck_module_user_first_name CHECK (LENGTH(BTRIM(first_name)) > 0),
    CONSTRAINT ck_module_user_last_name CHECK (LENGTH(BTRIM(last_name)) > 0),
    CONSTRAINT ck_module_user_role CHECK (
        role IN ('CITIZEN', 'AGENT', 'AREA_RESPONSIBLE', 'ADMIN')
    ),
    CONSTRAINT ck_module_user_area_required CHECK (
        role <> 'AREA_RESPONSIBLE' OR area_id IS NOT NULL
    ),
    CONSTRAINT ck_module_user_area_namespace CHECK (
        area_id IS NULL OR area_id IN ('M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9')
    )
);

CREATE INDEX idx_module_user_role_area ON module_users (role, area_id);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tickets WHERE assigned_agent_id IS NOT NULL) THEN
        RAISE EXCEPTION
            'V18 no puede convertir tickets.assigned_agent_id a BIGINT: existen valores sin mapping inequívoco a module_users.id';
    END IF;
END $$;

ALTER TABLE tickets
    ALTER COLUMN assigned_agent_id TYPE BIGINT USING NULL::BIGINT;

ALTER TABLE tickets
    ADD CONSTRAINT fk_ticket_assigned_agent
        FOREIGN KEY (assigned_agent_id) REFERENCES module_users (id);
