CREATE TABLE categories (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(150) NOT NULL,
                            description TEXT NOT NULL,
                            active BOOLEAN NOT NULL DEFAULT TRUE,
                            created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                            updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                            CONSTRAINT uk_category_name UNIQUE (name)
);

CREATE TABLE subcategories (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               category_id BIGINT NOT NULL,
                               name VARCHAR(150) NOT NULL,
                               description TEXT,
                               active BOOLEAN NOT NULL DEFAULT TRUE,
                               CONSTRAINT fk_subcategory_category
                                   FOREIGN KEY (category_id) REFERENCES categories (id),
                               CONSTRAINT uk_subcategory_category_name UNIQUE (category_id, name)
);

CREATE TABLE request_types (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               code VARCHAR(100) NOT NULL,
                               subcategory_id BIGINT NOT NULL,
                               name VARCHAR(200) NOT NULL,
                               description TEXT NOT NULL,
                               ticket_type VARCHAR(30) NOT NULL,
                               responsible_area_id VARCHAR(100) NOT NULL,
                               initial_priority VARCHAR(20) NOT NULL,
                               initial_risk VARCHAR(20) NOT NULL,
                               allows_anonymous BOOLEAN NOT NULL,
                               requires_location BOOLEAN NOT NULL,
                               active BOOLEAN NOT NULL DEFAULT TRUE,
                               CONSTRAINT fk_request_type_subcategory
                                   FOREIGN KEY (subcategory_id) REFERENCES subcategories (id),
                               CONSTRAINT uk_request_type_code UNIQUE (code),
                               CONSTRAINT ck_request_type_ticket_type CHECK (
                                   ticket_type IN ('COMPLAINT', 'REQUEST', 'INQUIRY', 'SUGGESTION')
                                   ),
                               CONSTRAINT ck_request_type_initial_priority CHECK (
                                   initial_priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')
                                   ),
                               CONSTRAINT ck_request_type_initial_risk CHECK (
                                   initial_risk IN ('VERY_LOW', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')
                                   )
);

CREATE TABLE neighborhood (
                              id UUID PRIMARY KEY,
                              name VARCHAR(255) NOT NULL,
                              population INTEGER NOT NULL,
                              CONSTRAINT uk_neighborhood_name UNIQUE (name)
);

CREATE TABLE tickets (
                         id UUID PRIMARY KEY,
                         public_id VARCHAR(50) NOT NULL,
                         tracking_code_hash VARCHAR(255) NOT NULL,
                         citizen_id BIGINT,
                         is_anonymous BOOLEAN NOT NULL,
                         request_type_id BIGINT NOT NULL,
                         ticket_type VARCHAR(30) NOT NULL,
                         responsible_area_id VARCHAR(100) NOT NULL,
                         assigned_agent_id VARCHAR(100),
                         summary VARCHAR(200) NOT NULL,
                         description TEXT NOT NULL,
                         form_data JSONB NOT NULL,
                         current_status VARCHAR(30) NOT NULL,
                         initial_priority VARCHAR(20) NOT NULL,
                         current_priority VARCHAR(20) NOT NULL,
                         affected_count INTEGER NOT NULL DEFAULT 0,
                         main_ticket_id UUID,
                         is_escalated BOOLEAN NOT NULL DEFAULT FALSE,
                         escalation_reason_code VARCHAR(30),
                         escalated_at TIMESTAMP WITH TIME ZONE,
                         reopen_count INTEGER NOT NULL DEFAULT 0,
                         status_changed_at TIMESTAMP WITH TIME ZONE NOT NULL,
                         resolution_confirmation_due_at TIMESTAMP WITH TIME ZONE,
                         preferred_notification_channel VARCHAR(30),
                         ticket_version INTEGER NOT NULL DEFAULT 1,
                         created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                         updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                         CONSTRAINT uk_ticket_public_id UNIQUE (public_id),
                         CONSTRAINT fk_ticket_request_type
                             FOREIGN KEY (request_type_id) REFERENCES request_types (id),
                         CONSTRAINT fk_ticket_main_ticket
                             FOREIGN KEY (main_ticket_id) REFERENCES tickets (id),
                         CONSTRAINT ck_ticket_anonymous_citizen CHECK (
                             (is_anonymous = TRUE AND citizen_id IS NULL)
                                 OR (is_anonymous = FALSE AND citizen_id IS NOT NULL)
                             ),
                         CONSTRAINT ck_ticket_type CHECK (
                             ticket_type IN ('COMPLAINT', 'REQUEST', 'INQUIRY', 'SUGGESTION')
                             ),
                         CONSTRAINT ck_ticket_current_status CHECK (
                             current_status IN (
                                                'REGISTERED', 'IN_REVIEW', 'ROUTED', 'IN_PROGRESS',
                                                'PENDING_INFORMATION', 'DUPLICATE', 'RESOLVED', 'CLOSED', 'CANCELLED'
                                 )
                             ),
                         CONSTRAINT ck_ticket_initial_priority CHECK (
                             initial_priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')
                             ),
                         CONSTRAINT ck_ticket_current_priority CHECK (
                             current_priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')
                             ),
                         CONSTRAINT ck_ticket_escalation_reason CHECK (
                             escalation_reason_code IS NULL OR escalation_reason_code IN (
                                                                                          'CRITICAL_PRIORITY', 'SLA_NEAR_DUE', 'SLA_BREACHED', 'MANUAL'
                                 )
                             )
);

CREATE INDEX idx_ticket_citizen_status
    ON tickets (citizen_id, current_status);
CREATE INDEX idx_ticket_area_status
    ON tickets (responsible_area_id, current_status);
CREATE INDEX idx_ticket_request_type
    ON tickets (request_type_id);
CREATE INDEX idx_ticket_main
    ON tickets (main_ticket_id);

CREATE TABLE ticket_locations (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  ticket_id UUID NOT NULL,
                                  address_line VARCHAR(300),
                                  street VARCHAR(150),
                                  street_number VARCHAR(30),
                                  neighborhood_id UUID,
                                  postal_code VARCHAR(20),
                                  latitude NUMERIC(9, 6),
                                  longitude NUMERIC(9, 6),
                                  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                  CONSTRAINT uk_ticket_location_ticket UNIQUE (ticket_id),
                                  CONSTRAINT fk_ticket_location_ticket
                                      FOREIGN KEY (ticket_id) REFERENCES tickets (id),
                                  CONSTRAINT fk_ticket_location_neighborhood
                                      FOREIGN KEY (neighborhood_id) REFERENCES neighborhood (id),
                                  CONSTRAINT ck_ticket_location_coordinates CHECK (
                                      (latitude IS NULL OR latitude BETWEEN -90 AND 90)
                                          AND (longitude IS NULL OR longitude BETWEEN -180 AND 180)
                                      )
);

CREATE TABLE ticket_messages (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 ticket_id UUID NOT NULL,
                                 author_type VARCHAR(30) NOT NULL,
                                 author_id VARCHAR(100),
                                 source_module_id VARCHAR(20),
                                 visibility VARCHAR(20) NOT NULL,
                                 text TEXT NOT NULL,
                                 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                 CONSTRAINT fk_ticket_message_ticket
                                     FOREIGN KEY (ticket_id) REFERENCES tickets (id),
                                 CONSTRAINT ck_ticket_message_author_type CHECK (
                                     author_type IN ('CITIZEN', 'AGENT', 'AREA_USER', 'SYSTEM')
                                     ),
                                 CONSTRAINT ck_ticket_message_visibility CHECK (
                                     visibility IN ('INTERNAL', 'PUBLIC')
                                     )
);

CREATE INDEX idx_ticket_message_ticket_created
    ON ticket_messages (ticket_id, created_at);

CREATE TABLE ticket_activities (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   ticket_id UUID NOT NULL,
                                   sequence INTEGER NOT NULL,
                                   action_type VARCHAR(50) NOT NULL,
                                   previous_status VARCHAR(30),
                                   new_status VARCHAR(30),
                                   actor_type VARCHAR(30) NOT NULL,
                                   actor_id VARCHAR(100),
                                   source_module_id VARCHAR(20),
                                   external_event_id UUID,
                                   reason_code VARCHAR(100),
                                   message TEXT,
                                   metadata JSONB,
                                   occurred_at TIMESTAMP WITH TIME ZONE,
                                   created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                   ticket_version INTEGER,
                                   CONSTRAINT fk_ticket_activity_ticket
                                       FOREIGN KEY (ticket_id) REFERENCES tickets (id),
                                   CONSTRAINT uk_ticket_activity_sequence UNIQUE (ticket_id, sequence),
                                   CONSTRAINT ck_ticket_activity_action_type CHECK (
                                       action_type IN (
                                                       'TICKET_CREATED', 'REVIEW_STARTED', 'STATE_CHANGED', 'ROUTED',
                                                       'RETURNED_BY_AREA', 'PRIORITY_CHANGED', 'ESCALATED',
                                                       'INFORMATION_REQUIRED', 'INFORMATION_PROVIDED', 'PROGRESS_REPORTED',
                                                       'DUPLICATE_LINKED', 'RESOLVED', 'REOPENED', 'CANCELLATION_REQUESTED',
                                                       'CANCELLATION_APPROVED', 'CANCELLATION_REJECTED', 'CANCELLED',
                                                       'CLOSED', 'PUBLIC_MESSAGE_SENT', 'INTERNAL_MESSAGE_ADDED',
                                                       'ATTACHMENT_ADDED'
                                           )
                                       ),
                                   CONSTRAINT ck_ticket_activity_previous_status CHECK (
                                       previous_status IS NULL OR previous_status IN (
                                                                                      'REGISTERED', 'IN_REVIEW', 'ROUTED', 'IN_PROGRESS',
                                                                                      'PENDING_INFORMATION', 'DUPLICATE', 'RESOLVED', 'CLOSED', 'CANCELLED'
                                           )
                                       ),
                                   CONSTRAINT ck_ticket_activity_new_status CHECK (
                                       new_status IS NULL OR new_status IN (
                                                                            'REGISTERED', 'IN_REVIEW', 'ROUTED', 'IN_PROGRESS',
                                                                            'PENDING_INFORMATION', 'DUPLICATE', 'RESOLVED', 'CLOSED', 'CANCELLED'
                                           )
                                       ),
                                   CONSTRAINT ck_ticket_activity_actor_type CHECK (
                                       actor_type IN ('CITIZEN', 'AGENT', 'AREA_USER', 'SYSTEM')
                                       )
);

CREATE INDEX idx_ticket_activity_ticket_sequence
    ON ticket_activities (ticket_id, sequence);