CREATE TABLE form_templates (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                request_type_id BIGINT NOT NULL,
                                version INTEGER NOT NULL,
                                active BOOLEAN NOT NULL DEFAULT TRUE,
                                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                CONSTRAINT fk_form_template_request_type
                                    FOREIGN KEY (request_type_id) REFERENCES request_types (id),
                                CONSTRAINT uk_form_template_request_type_version
                                    UNIQUE (request_type_id, version)
);

CREATE TABLE form_fields (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             form_template_id BIGINT NOT NULL,
                             code VARCHAR(100) NOT NULL,
                             label VARCHAR(200) NOT NULL,
                             type VARCHAR(20) NOT NULL,
                             required BOOLEAN NOT NULL DEFAULT FALSE,
                             display_order INTEGER NOT NULL,
                             config JSONB NOT NULL DEFAULT '{}'::jsonb,
                             CONSTRAINT fk_form_field_template
                                 FOREIGN KEY (form_template_id) REFERENCES form_templates (id),
                             CONSTRAINT uk_form_field_template_code
                                 UNIQUE (form_template_id, code),
                             CONSTRAINT ck_form_field_type
                                 CHECK (type IN ('TEXT', 'TEXTAREA', 'SELECT', 'BOOLEAN', 'NUMBER', 'DATE'))
);

CREATE INDEX idx_form_field_template_order
    ON form_fields (form_template_id, display_order);