ALTER TABLE information_requests
    DROP CONSTRAINT ck_information_request_request_actor;

ALTER TABLE information_requests
    ADD CONSTRAINT ck_information_request_request_actor CHECK (
        requested_by_actor_type IN (
            'CITIZEN', 'AGENT', 'AREA_RESPONSIBLE', 'ADMIN', 'EXTERNAL_USER', 'SYSTEM'
        )
    );

ALTER TABLE information_requests
    DROP CONSTRAINT ck_information_request_answer_fields;

ALTER TABLE information_requests
    ADD CONSTRAINT ck_information_request_answer_fields CHECK (
        (status = 'ANSWERED'
            AND answered_by_type IS NOT NULL
            AND answered_at IS NOT NULL)
        OR
        (status <> 'ANSWERED'
            AND response_message IS NULL
            AND answered_by_type IS NULL
            AND answered_by_id IS NULL
            AND answered_at IS NULL)
    );

CREATE TABLE information_request_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    information_request_id UUID NOT NULL,
    attachment_id BIGINT NOT NULL,
    role VARCHAR(30) NOT NULL,
    CONSTRAINT fk_information_request_attachment_request
        FOREIGN KEY (information_request_id) REFERENCES information_requests (id) ON DELETE CASCADE,
    CONSTRAINT fk_information_request_attachment_attachment
        FOREIGN KEY (attachment_id) REFERENCES attachments (id),
    CONSTRAINT uk_information_request_attachment
        UNIQUE (information_request_id, attachment_id),
    CONSTRAINT ck_information_request_attachment_role
        CHECK (role IN ('REQUEST_CONTEXT', 'RESPONSE'))
);

CREATE INDEX idx_information_request_attachment_request_role
    ON information_request_attachments (information_request_id, role);
