CREATE TABLE risk_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_field_id BIGINT NOT NULL,
    operator VARCHAR(30) NOT NULL,
    expected_value JSONB,
    value_from NUMERIC,
    value_to NUMERIC,
    risk_increment SMALLINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_risk_rule_form_field
        FOREIGN KEY (form_field_id) REFERENCES form_fields (id),
    CONSTRAINT ck_risk_rule_operator CHECK (
        operator IN ('EQUALS', 'BETWEEN', 'GREATER_THAN', 'LESS_THAN', 'IN')
    ),
    CONSTRAINT ck_risk_rule_increment CHECK (
        risk_increment BETWEEN 0 AND 100
    ),
    CONSTRAINT ck_risk_rule_operands CHECK (
        (operator = 'EQUALS'
            AND expected_value IS NOT NULL
            AND expected_value <> 'null'::jsonb
            AND value_from IS NULL
            AND value_to IS NULL)
        OR
        (operator = 'IN'
            AND jsonb_typeof(expected_value) = 'array'
            AND value_from IS NULL
            AND value_to IS NULL)
        OR
        (operator = 'BETWEEN'
            AND expected_value IS NULL
            AND value_from IS NOT NULL
            AND value_to IS NOT NULL
            AND value_from <= value_to)
        OR
        (operator = 'GREATER_THAN'
            AND expected_value IS NULL
            AND value_from IS NOT NULL
            AND value_to IS NULL)
        OR
        (operator = 'LESS_THAN'
            AND expected_value IS NULL
            AND value_from IS NULL
            AND value_to IS NOT NULL)
    )
);

CREATE INDEX idx_risk_rule_form_field_active
    ON risk_rules (form_field_id, active);

ALTER TABLE tickets ADD COLUMN form_template_id BIGINT;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM form_fields ff
        WHERE ff.config ? 'riskScore'
          AND (
              ff.type <> 'BOOLEAN'
              OR jsonb_typeof(ff.config -> 'riskScore') <> 'number'
              OR (ff.config ->> 'riskScore')::NUMERIC NOT IN (1, 2, 2.5, 3, 4, 5)
          )
    ) THEN
        RAISE EXCEPTION
            'V7 no puede migrar: existe un riskScore directo con tipo, formato o valor no soportado';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM form_fields ff
        CROSS JOIN LATERAL jsonb_array_elements(
            CASE
                WHEN jsonb_typeof(ff.config -> 'options') = 'array'
                    THEN ff.config -> 'options'
                ELSE '[]'::jsonb
            END
        ) option_value
        WHERE option_value ? 'riskScore'
          AND (
              ff.type <> 'SELECT'
              OR NOT option_value ? 'value'
              OR jsonb_typeof(option_value -> 'riskScore') <> 'number'
              OR (option_value ->> 'riskScore')::NUMERIC NOT IN (1, 2, 2.5, 3, 4, 5)
          )
    ) THEN
        RAISE EXCEPTION
            'V7 no puede migrar: existe un riskScore de opción con tipo, formato o valor no soportado';
    END IF;
END $$;

INSERT INTO risk_rules (
    form_field_id,
    operator,
    expected_value,
    value_from,
    value_to,
    risk_increment,
    active
)
SELECT
    ff.id,
    'EQUALS',
    'true'::jsonb,
    NULL,
    NULL,
    CASE (ff.config ->> 'riskScore')::NUMERIC
        WHEN 1 THEN 5
        WHEN 2 THEN 10
        WHEN 2.5 THEN 13
        WHEN 3 THEN 18
        WHEN 4 THEN 27
        WHEN 5 THEN 36
    END,
    TRUE
FROM form_fields ff
WHERE ff.config ? 'riskScore';

INSERT INTO risk_rules (
    form_field_id,
    operator,
    expected_value,
    value_from,
    value_to,
    risk_increment,
    active
)
SELECT
    ff.id,
    'EQUALS',
    to_jsonb(option_value ->> 'value'),
    NULL,
    NULL,
    CASE (option_value ->> 'riskScore')::NUMERIC
        WHEN 1 THEN 5
        WHEN 2 THEN 10
        WHEN 2.5 THEN 13
        WHEN 3 THEN 18
        WHEN 4 THEN 27
        WHEN 5 THEN 36
    END,
    TRUE
FROM form_fields ff
CROSS JOIN LATERAL jsonb_array_elements(
    CASE
        WHEN jsonb_typeof(ff.config -> 'options') = 'array'
            THEN ff.config -> 'options'
        ELSE '[]'::jsonb
    END
) option_value
WHERE option_value ? 'riskScore';

DO $$
DECLARE
    actual_total BIGINT;
    actual_5 BIGINT;
    actual_10 BIGINT;
    actual_13 BIGINT;
    actual_18 BIGINT;
    actual_27 BIGINT;
    actual_36 BIGINT;
BEGIN
    SELECT
        COUNT(*),
        COUNT(*) FILTER (WHERE risk_increment = 5),
        COUNT(*) FILTER (WHERE risk_increment = 10),
        COUNT(*) FILTER (WHERE risk_increment = 13),
        COUNT(*) FILTER (WHERE risk_increment = 18),
        COUNT(*) FILTER (WHERE risk_increment = 27),
        COUNT(*) FILTER (WHERE risk_increment = 36)
    INTO actual_total, actual_5, actual_10, actual_13, actual_18, actual_27, actual_36
    FROM risk_rules;

    IF actual_total <> 303
        OR actual_5 <> 35
        OR actual_10 <> 39
        OR actual_13 <> 10
        OR actual_18 <> 54
        OR actual_27 <> 75
        OR actual_36 <> 90 THEN
        RAISE EXCEPTION
            'V7 abortada: se esperaban 303 RiskRule con distribución 5:35, 10:39, 13:10, 18:54, 27:75, 36:90; se obtuvieron total %, 5:%, 10:%, 13:%, 18:%, 27:%, 36:%',
            actual_total, actual_5, actual_10, actual_13, actual_18, actual_27, actual_36;
    END IF;
END $$;

UPDATE form_fields
SET config = config - 'riskScore'
WHERE config ? 'riskScore';

UPDATE form_fields ff
SET config = jsonb_set(ff.config, '{options}', cleaned.options, FALSE)
FROM (
    SELECT
        source.id,
        jsonb_agg(option_value - 'riskScore' ORDER BY option_order) AS options
    FROM form_fields source
    CROSS JOIN LATERAL jsonb_array_elements(
        CASE
            WHEN jsonb_typeof(source.config -> 'options') = 'array'
                THEN source.config -> 'options'
            ELSE '[]'::jsonb
        END
    ) WITH ORDINALITY AS option_entry(option_value, option_order)
    GROUP BY source.id
    HAVING BOOL_OR(option_value ? 'riskScore')
) cleaned
WHERE cleaned.id = ff.id;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM form_fields
        WHERE jsonb_path_exists(config, '$.**.riskScore')
    ) THEN
        RAISE EXCEPTION 'V7 abortada: quedaron riskScore residuales en form_fields.config';
    END IF;
END $$;

ALTER TABLE form_fields DROP COLUMN required;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM tickets ticket
        JOIN (
            SELECT request_type_id, COUNT(*) AS template_count
            FROM form_templates
            GROUP BY request_type_id
        ) template_counts
          ON template_counts.request_type_id = ticket.request_type_id
        WHERE ticket.form_template_id IS NULL
          AND template_counts.template_count > 1
    ) THEN
        RAISE EXCEPTION
            'V7 no puede inferir form_template_id: existen tickets históricos para RequestType con múltiples FormTemplate';
    END IF;
END $$;

UPDATE tickets ticket
SET form_template_id = single_template.form_template_id
FROM (
    SELECT request_type_id, MIN(id) AS form_template_id
    FROM form_templates
    GROUP BY request_type_id
    HAVING COUNT(*) = 1
) single_template
WHERE ticket.request_type_id = single_template.request_type_id
  AND ticket.form_template_id IS NULL;

ALTER TABLE form_templates
    ADD CONSTRAINT uk_form_template_id_request_type UNIQUE (id, request_type_id);

ALTER TABLE tickets
    ADD CONSTRAINT fk_ticket_form_template_request_type
        FOREIGN KEY (form_template_id, request_type_id)
        REFERENCES form_templates (id, request_type_id);
