CREATE TABLE attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id UUID NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(150) NOT NULL,
    size_bytes BIGINT NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    visibility VARCHAR(20) NOT NULL,
    uploaded_by_type VARCHAR(30) NOT NULL,
    uploaded_by_id VARCHAR(100),
    source_module_id VARCHAR(20),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_attachment_ticket
        FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT uk_attachment_storage_key UNIQUE (storage_key),
    CONSTRAINT ck_attachment_file_name
        CHECK (LENGTH(BTRIM(file_name)) > 0),
    CONSTRAINT ck_attachment_content_type
        CHECK (LENGTH(BTRIM(content_type)) > 0),
    CONSTRAINT ck_attachment_size
        CHECK (size_bytes > 0),
    CONSTRAINT ck_attachment_storage_key
        CHECK (LENGTH(BTRIM(storage_key)) > 0),
    CONSTRAINT ck_attachment_visibility
        CHECK (visibility IN ('PUBLIC', 'INTERNAL')),
    CONSTRAINT ck_attachment_uploaded_by_type
        CHECK (uploaded_by_type IN (
            'CITIZEN', 'AGENT', 'AREA_RESPONSIBLE', 'ADMIN', 'EXTERNAL_USER', 'SYSTEM'
        ))
);

CREATE INDEX idx_attachment_ticket_created
    ON attachments (ticket_id, created_at);
